#!/bin/bash

# Kick off the angular build process.
if [ "$1" = "Prod" ] || [ "$1" = "prod" ]; then
	ng build --prod --extractCss
else
	ng build --extractCss
fi



# Wipe the existing Content subfolders and then recreate them.
echo "Removing existing wwwroot/Styles directory"
rm -rf wwwroot/Styles
echo "Removing existing wwwroot/Scripts directory"
rm -rf wwwroot/Scripts
echo "Removing existing wwwroot/Images directory"
rm -rf wwwroot/Images

echo "Creating Directory wwwroot/Styles"
mkdir wwwroot/Styles
echo "Creating Directory wwwroot/Scripts"
mkdir wwwroot/Scripts
echo "Creating Directory wwwroot/Images"
mkdir wwwroot/Images



# Move the files.
for FILE in $(ls -1 AngularBuildDir | grep ".css"); do
	echo "Moving AngularBuildDir/${FILE} to wwwroot/Styles/${FILE}"
	mv AngularBuildDir/${FILE} wwwroot/Styles/${FILE}
done
for FILE in $(ls -1 AngularBuildDir | grep ".js"); do
	echo "Moving AngularBuildDir/${FILE} to wwwroot/Scripts/${FILE}"
	mv AngularBuildDir/${FILE} wwwroot/Scripts/${FILE}
done
for FILE in $(ls -1 AngularBuildDir/Content | grep ".ico"); do
	echo "Moving AngularBuildDir/Content/${FILE} to wwwroot/Images/${FILE}"
	mv AngularBuildDir/Content/${FILE} wwwroot/Images/${FILE}
done



# This is hackish and a little ugly but pretty prints and fixes the output file nicely.
echo "Fix and move the sites layout file"
mv AngularBuildDir/_Layout.cshtml Views/Shared/_Layout.cshtml
sed -i -e 's/<link rel="stylesheet" href="styles/  <link rel="stylesheet" href="~\/Styles\/styles/g' Views/Shared/_Layout.cshtml
sed -i -e 's/<\/head>/\'$'\n<\/head>/g' Views/Shared/_Layout.cshtml
sed -i -e 's/<\/script></<\/script>\'$'\n</g' Views/Shared/_Layout.cshtml
sed -i -e 's/<script src="runtime-es/  <script src="~\/Scripts\/runtime-es/g' Views/Shared/_Layout.cshtml
sed -i -e 's/<script src="polyfills-es/  <script src="~\/Scripts\/polyfills-es/g' Views/Shared/_Layout.cshtml
sed -i -e 's/<script src="vendor-es/  <script src="~\/Scripts\/vendor-es/g' Views/Shared/_Layout.cshtml
sed -i -e 's/<script src="main-es/  <script src="~\/Scripts\/main-es/g' Views/Shared/_Layout.cshtml



#Cleanup for production build run
if [ "$1" = "Prod" ] || [ "$1" = "prod" ]; then
	echo "Removing unneeded autogenerated license file from build directory"
	rm AngularBuildDir/3rdpartylicenses.txt
fi



# Cleanup the directories if all the files have been moved.
if [ "$(ls -A AngularBuildDir/Content)" ]; then
     echo "AngularBuildDir/Content is not Empty"
else
    rmdir AngularBuildDir/Content
fi
if [ "$(ls -A AngularBuildDir)" ]; then
     echo "AngularBuildDir is not Empty"
else
    rmdir AngularBuildDir
fi

